---
abstract: 'Role to add validation to a class'
author:
  - 'Binary.com <fayland@binary.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Validatable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Moose: 0
  Scalar::Util: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/binary-com/perl-MooX-Role-Validatable/issues
  homepage: https://github.com/binary-com/perl-MooX-Role-Validatable
  repository: https://github.com/binary-com/perl-MooX-Role-Validatable.git
version: 0.09
x_contributors:
  - 'Jean-Yves Sireau <jy@binary.com>'
